### ISSUE TITLE
API PR is missing check?

### ISSUE THREAD

**Issue by nornagon** [electron/cation#122]
This API PR doesn't seem to have the API LGTM check attached: https://github.com/electron/electron/pull/35902

**Comment by nornagon** [comment]
this one too: https://github.com/electron/electron/pull/35737

**Comment by nornagon** [comment]
and this one: https://github.com/electron/electron/pull/34980

**Comment by codebytere** [comment]
Closed in https://github.com/electron/cation/commit/c73d4042aa60ca5772bf4873e5ffc881d54311bf
