### ISSUE TITLE
Change requests with API LGTM appear as both "Approved" and "Requested Changes"

### ISSUE THREAD

**Issue by erickzhao** [electron/cation#136]
See https://github.com/electron/electron/pull/37535/checks?check_run_id=12028226514

The original review from @~nornagon was of this format:

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/16010076/225755546-6a1095ee-ff45-40f1-aae6-aceb6ceb052e.png">

Link: https://github.com/electron/electron/pull/37535#pullrequestreview-1337900204

**Comment by itsananderson** [comment]
I think this issue is resolved now, because we don't look at "Requested Changes" for API review state after https://github.com/electron/cation/pull/163 landed
